name: spellcheck
on: [push, pull_request]
jobs:
  spellcheck:
    name: Markdown spellchecker
    runs-on: ubuntu-latest
    steps:
    - name: Check out code.
      uses: actions/checkout@v2
    - name: GitHub Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.5.0
