name: spellchecker
on: [push, pull_request]
jobs:
  build:
    name: Markdown spellchecker
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.5.0
