name: Check Spelling
on: [push, pull_request]

jobs:
  build:
    # Job name
    name: spell check
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.2.0
